name: Docker Image CI

on:
  push:
    branches: ["main"] # 根据你的主分支名称调整

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Alibaba Cloud Registry
        run: |
          echo ${{ secrets.ALIYUN_PASSWORD }} | docker login --username=${{ secrets.ALIYUN_USERNAME }} --password-stdin registry.cn-beijing.aliyuncs.com

      - name: Build Docker image
        run: |
          docker build -t news-api:latest -f ./Dockerfile .

      - name: Tag Docker image
        run: |
          docker tag news-api:latest registry.cn-beijing.aliyuncs.com/teddymail/news-api:latest
          docker tag news-api:latest registry.cn-beijing.aliyuncs.com/teddymail/news-api:${{ github.sha }}

      - name: Push Docker image to Alibaba Cloud
        run: |
          docker push registry.cn-beijing.aliyuncs.com/teddymail/news-api:latest
          docker push registry.cn-beijing.aliyuncs.com/teddymail/news-api:${{ github.sha }}

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          port: 2538
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Login to Alibaba Cloud Registry
            echo ${{ secrets.ALIYUN_PASSWORD }} | docker login --username=${{ secrets.ALIYUN_USERNAME }} --password-stdin registry.cn-beijing.aliyuncs.com
            # Pull Docker image
            docker pull registry.cn-beijing.aliyuncs.com/teddymail/news-api:${{ github.sha }}
            # Ensure the container does not exist before stopping and removing
            docker ps -a | grep news-api || true
            docker stop news-api || true
            docker rm news-api || true
            # Run the container
            docker run -d \
              --name news-api \
              -p 8099:8099 \
              -e PORT=8099 \
              -e DB_DSN="${{ secrets.DB_DSN }}" \
              registry.cn-beijing.aliyuncs.com/teddymail/news-api:latest